fix maven jar-with-dependencies, needs vendor name for library javax.imageio.spi.ImageReaderSpi
to avoid error:
java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReaderSpi could not be instantiated

...
Caused by: java.lang.IllegalArgumentException: vendorName == null!